project_id = "coreflow-pdv"

[functions.emitir-nfce]
verify_jwt = true

[functions.cancelar-nfce]
verify_jwt = true

[functions.consultar-nfce]
verify_jwt = true

[functions.reenviar-nfce]
verify_jwt = true

[functions.fiscal-document-files]
verify_jwt = true

[functions.fiscal-provider-status]
verify_jwt = true

[functions.core-admin-create-retailer]
verify_jwt = true

[functions.core-admin-create-user]
verify_jwt = true

[functions.core-admin-update-access]
verify_jwt = true

[functions.core-admin-upsert-domain]
verify_jwt = true

[functions.fiscal-settings]
verify_jwt = true

[functions.company-create-user]
verify_jwt = true

[functions.company-update-user]
verify_jwt = true
